select * from t_emp
select fduty  from t_emp 
select right(fid,3),fname from t_submessage where ftypeid = 29
select * from job_grade
insert all into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL','001','总经理','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL','002','副总经理','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL','003','部长','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL','004','副部长','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL','005','助理员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL','006','科长','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL','007','副科长','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL','008','技术员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '009',' 主管会计','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '012','质检员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '010','会计','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '011',' 出纳','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '013','营销外贸业务专员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '014','操作工','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '000',' 董事长','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '015','组长','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '016',' 副组长','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '017',' 主管','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '018','副主管','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '019',' 技术总监','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '020','营销总监','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '021','总经理助理员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '022','ERP专员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '023','ERP助理员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '024','网络管理员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '025','人事专员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '026','维修工','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '027','仓管员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '028','保安','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '029','司机','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '030','体系项目专员','EPAYROLL')
 into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '031', ' 保洁员','EPAYROLL')
 into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '032', ' 采购专员','EPAYROLL')
 into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '033', ' 计划专员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '034', ' 助理','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '035', '营销内贸业务专员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '036', '软件实施工程师','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '037', '质量体系专员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '038', '采购工程师','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '039', '软件开发工程师','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '040', '生管','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '041', '产品助理工程师','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '042', '体系专员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '043', '助理工程师','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '044', '劳资专员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '045', '代理副组长','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '046', '市场开发科主管','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '047', '总经理助理员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '048', '冲压调模','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '049', '部长助理','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '050', '企业文化宣传专员','EPAYROLL')
into job_grade(com_cd,job_grade_cd,l_abbr_name,user_emp) values( 'EPAYROLL', '051', '后勤保障专员','EPAYROLL')
select 1 from dual
select * from job_grade

update job_grade set e_abbr_name=l_abbr_name,e_full_name = l_abbr_name,l_full_name=l_abbr_name 
update job_grade set ATT_TARGET = 'Y' where create_DATE > '01-AUG-2018'


